
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import RouterV3ContractArtifactJson from './router_contract-RouterV3.json' with { type: 'json' };
export const RouterV3ContractArtifact = loadContractArtifact(RouterV3ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract RouterV3;
 */
export class RouterV3Contract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, RouterV3ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, RouterV3Contract.artifact, wallet) as Promise<RouterV3Contract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, _factory: AztecAddressLike) {
    return new DeployMethod<RouterV3Contract>(PublicKeys.default(), wallet, RouterV3ContractArtifact, RouterV3Contract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, _factory: AztecAddressLike) {
    return new DeployMethod<RouterV3Contract>(publicKeys, wallet, RouterV3ContractArtifact, RouterV3Contract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof RouterV3Contract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<RouterV3Contract['methods'][M]>
  ) {
    return new DeployMethod<RouterV3Contract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      RouterV3ContractArtifact,
      RouterV3Contract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return RouterV3ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(RouterV3ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'factory' | 'liquidityToBeMinted'> {
      return {
        factory: {
      slot: new Fr(1n),
    },
liquidityToBeMinted: {
      slot: new Fr(2n),
    }
      } as ContractStorageLayout<'factory' | 'liquidityToBeMinted'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(0),
        },
UintNote: {
          id: new NoteSelector(1),
        },
ValueNote: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _getPool(tokenA: struct, tokenB: struct, fee: integer) */
    _getPool: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _mint_private(tokenA: struct, tokenB: struct, fee: field, tickLower: integer, tickUpper: integer, isTickLowerNeg: boolean, isTickUpperNeg: boolean, recipient: struct, amount0Min: field, amount1Min: field, lte: boolean, nonce: field) */
    _mint_private: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike, tickLower: (bigint | number), tickUpper: (bigint | number), isTickLowerNeg: boolean, isTickUpperNeg: boolean, recipient: AztecAddressLike, amount0Min: FieldLike, amount1Min: FieldLike, lte: boolean, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** addLiquidity_private(tokenA: struct, tokenB: struct, fee: field, recipient: struct, tickLower: integer, tickUpper: integer, isTickLowerNeg: boolean, isTickUpperNeg: boolean, amount0Desired: field, amount1Desired: field, amount0Min: field, amount1Min: field, lte: boolean, nonce: field, secret: field, sqrtPriceX96: field) */
    addLiquidity_private: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike, recipient: AztecAddressLike, tickLower: (bigint | number), tickUpper: (bigint | number), isTickLowerNeg: boolean, isTickUpperNeg: boolean, amount0Desired: FieldLike, amount1Desired: FieldLike, amount0Min: FieldLike, amount1Min: FieldLike, lte: boolean, nonce: FieldLike, secret: FieldLike, sqrtPriceX96: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(_factory: struct) */
    constructor: ((_factory: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** currentTick(tokenA: struct, tokenB: struct, fee: integer) */
    currentTick: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** toBeMinted(tokenA: struct, tokenB: struct, fee: integer) */
    toBeMinted: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
