
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  loadContractArtifact,
  loadContractArtifactForPublic,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import FactoryV3ContractArtifactJson from './factory_contract-FactoryV3.json' with { type: 'json' };
export const FactoryV3ContractArtifact = loadContractArtifact(FactoryV3ContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract FactoryV3;
 */
export class FactoryV3Contract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, FactoryV3ContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, FactoryV3Contract.artifact, wallet) as Promise<FactoryV3Contract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, lpToken: AztecAddressLike, lp_contract_id: FieldLike) {
    return new DeployMethod<FactoryV3Contract>(PublicKeys.default(), wallet, FactoryV3ContractArtifact, FactoryV3Contract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, admin: AztecAddressLike, lpToken: AztecAddressLike, lp_contract_id: FieldLike) {
    return new DeployMethod<FactoryV3Contract>(publicKeys, wallet, FactoryV3ContractArtifact, FactoryV3Contract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FactoryV3Contract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FactoryV3Contract['methods'][M]>
  ) {
    return new DeployMethod<FactoryV3Contract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FactoryV3ContractArtifact,
      FactoryV3Contract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FactoryV3ContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(FactoryV3ContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'pools' | 'feeAmountTickSpacing' | 'ticks' | 'approved_lps' | 'protocolFees' | 'positions' | 'tickBitmap' | 'observations' | 'observationByIndex'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
pools: {
      slot: new Fr(2n),
    },
feeAmountTickSpacing: {
      slot: new Fr(3n),
    },
ticks: {
      slot: new Fr(4n),
    },
approved_lps: {
      slot: new Fr(5n),
    },
protocolFees: {
      slot: new Fr(6n),
    },
positions: {
      slot: new Fr(7n),
    },
tickBitmap: {
      slot: new Fr(8n),
    },
observations: {
      slot: new Fr(9n),
    },
observationByIndex: {
      slot: new Fr(10n),
    }
      } as ContractStorageLayout<'admin' | 'pools' | 'feeAmountTickSpacing' | 'ticks' | 'approved_lps' | 'protocolFees' | 'positions' | 'tickBitmap' | 'observations' | 'observationByIndex'>;
    }
    

  public static get notes(): ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'> {
    return {
      AddressNote: {
          id: new NoteSelector(0),
        },
UintNote: {
          id: new NoteSelector(1),
        },
ValueNote: {
          id: new NoteSelector(2),
        }
    } as ContractNotes<'AddressNote' | 'UintNote' | 'ValueNote'>;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** _createPool(tokenA: struct, tokenB: struct, fee: field) */
    _createPool: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** _mint(tokenA: struct, tokenB: struct, fee: integer, recipient: struct, tickLower: integer, tickUpper: integer, isTickLowerNeg: boolean, isTickUpperNeg: boolean, amount: integer, lte: boolean, getSqrtRatioAtTickUpper: field, getSqrtRatioAtTickLower: field, nonce: field) */
    _mint: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number), recipient: AztecAddressLike, tickLower: (bigint | number), tickUpper: (bigint | number), isTickLowerNeg: boolean, isTickUpperNeg: boolean, amount: (bigint | number), lte: boolean, getSqrtRatioAtTickUpper: FieldLike, getSqrtRatioAtTickLower: FieldLike, nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** checkFeeAmount(fee: field) */
    checkFeeAmount: ((fee: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** collectProtocol(tokenA: struct, tokenB: struct, fee: field, recipient: struct, amount0Requested: integer, amount1Requested: integer, nonce: field) */
    collectProtocol: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike, recipient: AztecAddressLike, amount0Requested: (bigint | number), amount1Requested: (bigint | number), nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, lpToken: struct, lp_contract_id: field) */
    constructor: ((admin: AztecAddressLike, lpToken: AztecAddressLike, lp_contract_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** createPool_private(tokenA: struct, tokenB: struct, fee: field) */
    createPool_private: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** enableFeeAmount(fee: field, tickSpacing: field) */
    enableFeeAmount: ((fee: FieldLike, tickSpacing: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** getPool(tokenA: struct, tokenB: struct, fee: integer) */
    getPool: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** getTickSpacing(fee: field) */
    getTickSpacing: ((fee: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** initialize_pool(tokenA: struct, tokenB: struct, fee: field, sqrtPriceX96: field, tick: field, isNegTick: boolean) */
    initialize_pool: ((tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: FieldLike, sqrtPriceX96: FieldLike, tick: FieldLike, isNegTick: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_admin(newAdmin: struct) */
    set_admin: ((newAdmin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_rate(rate: field, tokenA: struct, tokenB: struct, fee: integer) */
    set_rate: ((rate: FieldLike, tokenA: AztecAddressLike, tokenB: AztecAddressLike, fee: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
